# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bfdefa161808c9c4475d24bfdf9ea539631a813a44484bc9d7630866aa808fc9aec874de9ec31da8cd30596856bc9896b95a5b7d989948cfdac94d44645b733

test:
  secret_key_base: 5e743c7960b4e51c46f6c0b4437363d45be7451841b86bca2325179e9c197d58c12e40f6f0225bcf07a2f09fd4f9ed053d95b9e1b7289d49fcb77ed601266094

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
